#!/usr/bin/env bash
#
# Packages the add-on for Minecraft Bedrock.
#
#   ./tools/build.sh              offline build - local brain only, works on
#                                 phones, consoles, Realms and single-player
#   ./tools/build.sh --claude     adds @minecraft/server-net so citizens can
#                                 think through the Claude bridge. Bedrock
#                                 Dedicated Server only - see docs/CLAUDE_SETUP.md
#
# Output lands in dist/:
#   AI_Citizens.mcaddon           both packs - double-click to install
#   AI_Citizens_BP.mcpack         behaviour pack on its own
#   AI_Citizens_RP.mcpack         resource pack on its own
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

WITH_CLAUDE=0
for arg in "$@"; do
  case "$arg" in
    --claude) WITH_CLAUDE=1 ;;
    --offline) WITH_CLAUDE=0 ;;
    -h|--help) sed -n '2,20p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 1 ;;
  esac
done

BP="packs/AI_Citizens_BP"
RP="packs/AI_Citizens_RP"
TRANSPORT="$BP/scripts/brain/transport.js"
MANIFEST="$BP/manifest.json"

# --- regenerate the parts that are generated ------------------------------
echo "==> generating entities and textures"
python3 tools/generate_entities.py
[ -f "$RP/textures/entity/ai_citizen/citizen_00.png" ] || python3 tools/generate_skins.py

# --- select the transport -------------------------------------------------
if [ "$WITH_CLAUDE" -eq 1 ]; then
  echo "==> enabling the Claude bridge (@minecraft/server-net)"
  cat > "$TRANSPORT" <<'EOF'
/**
 * Transport selector - CLAUDE BUILD.
 *
 * Generated by tools/build.sh --claude. Runs on Bedrock Dedicated Server only;
 * the server owner must also grant this pack network permission. See
 * docs/CLAUDE_SETUP.md. Re-run tools/build.sh with no flags to go back offline.
 */
export { NET_AVAILABLE, postJson, transportName } from "./transport_net.js";
EOF
  python3 - "$MANIFEST" <<'EOF'
import json, sys
path = sys.argv[1]
m = json.load(open(path))
deps = m.setdefault("dependencies", [])
if not any(d.get("module_name") == "@minecraft/server-net" for d in deps):
    deps.append({"module_name": "@minecraft/server-net", "version": "1.0.0-beta"})
json.dump(m, open(path, "w"), indent=2)
open(path, "a").write("\n")
EOF
else
  echo "==> offline build (local brain)"
  cat > "$TRANSPORT" <<'EOF'
/**
 * Transport selector.
 *
 * Re-exports the stub by default. `tools/build.sh --claude` rewrites this file
 * to point at ./transport_net.js. Keep the export surface identical in both.
 */
export { NET_AVAILABLE, postJson, transportName } from "./transport_none.js";
EOF
  python3 - "$MANIFEST" <<'EOF'
import json, sys
path = sys.argv[1]
m = json.load(open(path))
m["dependencies"] = [d for d in m.get("dependencies", [])
                     if d.get("module_name") != "@minecraft/server-net"]
json.dump(m, open(path, "w"), indent=2)
open(path, "a").write("\n")
EOF
fi

# --- check before packaging ----------------------------------------------
echo "==> validating"
node tools/validate.mjs

# --- package --------------------------------------------------------------
echo "==> packaging"
rm -rf dist
mkdir -p dist

python3 - <<'EOF'
import os, zipfile

def add_tree(zf, src, prefix):
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__", "node_modules")]
        for name in files:
            if name.endswith((".pyc", ".DS_Store")):
                continue
            full = os.path.join(root, name)
            rel = os.path.relpath(full, src)
            zf.write(full, os.path.join(prefix, rel) if prefix else rel)

def pack(out, entries):
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for src, prefix in entries:
            add_tree(zf, src, prefix)
    print("   %-34s %6.1f KB" % (out, os.path.getsize(out) / 1024))

pack("dist/AI_Citizens_BP.mcpack", [("packs/AI_Citizens_BP", "")])
pack("dist/AI_Citizens_RP.mcpack", [("packs/AI_Citizens_RP", "")])
pack("dist/AI_Citizens.mcaddon", [
    ("packs/AI_Citizens_BP", "AI_Citizens_BP"),
    ("packs/AI_Citizens_RP", "AI_Citizens_RP"),
])
EOF

echo
if [ "$WITH_CLAUDE" -eq 1 ]; then
  echo "Built with the Claude bridge enabled."
  echo "  Next: start the bridge (cd bridge && npm install && npm start)"
  echo "        and read docs/CLAUDE_SETUP.md for the server permission step."
else
  echo "Built for offline play (local brain)."
  echo "  Citizens think, talk, build and take orders with no network at all."
  echo "  For Claude-powered minds: ./tools/build.sh --claude"
fi
echo "  Install: open dist/AI_Citizens.mcaddon with Minecraft."
