#!/usr/bin/env bash
#
# Packages the add-on for Minecraft Bedrock.
#
#   ./tools/build.sh              the add-on. One file, everything in it.
#                                 Imports on any Minecraft from 1.21.80 onwards,
#                                 needs no experiments, and survives updates.
#                                 You talk to citizens with /ai:tell.
#
#   SERVER_VERSION=2.1.0-beta MIN_ENGINE=1.21.90 ./tools/build.sh
#                                 same add-on with chat listening, pinned to one
#                                 Minecraft release. Only do this when you know
#                                 the exact version you are building for - a
#                                 beta pin that does not match refuses to import.
#
#   ./tools/build.sh --claude     adds @minecraft/server-net so citizens think
#                                 through the Claude bridge. Bedrock Dedicated
#                                 Server only - see docs/CLAUDE_SETUP.md.
#
# Why chat is not on by default: reading chat is only possible through the beta
# script API, and every way of asking for it - a pinned "-beta" number or the
# dynamic "beta" string - is tied to a particular range of Minecraft releases.
# Get it wrong and the manifest will not parse, which is an import failure
# rather than a missing feature. The default asks for nothing version-specific.
#
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

WITH_CLAUDE=0
STABLE=1          # the import-safe configuration is now the only default
for arg in "$@"; do
  case "$arg" in
    --claude) WITH_CLAUDE=1 ;;
    -h|--help) sed -n '2,24p' "$0" | sed 's/^# \{0,1\}//'; exit 0 ;;
    *) echo "unknown option: $arg" >&2; exit 1 ;;
  esac
done

BP="packs/AI_Citizens_BP"
RP="packs/AI_Citizens_RP"
TRANSPORT="$BP/scripts/brain/transport.js"

echo "==> generating entities and textures"
python3 tools/generate_entities.py
[ -f "$RP/textures/entity/ai_citizen/citizen_00.png" ] || python3 tools/generate_skins.py

# --------------------------------------------------------------------------
configure() {
  local stable="$1" with_claude="$2"

  if [ "$with_claude" -eq 1 ]; then
    cat > "$TRANSPORT" <<'EOF'
/**
 * Transport selector - CLAUDE BUILD.
 *
 * Generated by tools/build.sh --claude. Runs on Bedrock Dedicated Server only;
 * the server owner must also grant this pack network permission. See
 * docs/CLAUDE_SETUP.md. Re-run tools/build.sh without --claude to go back.
 */
export { NET_AVAILABLE, postJson, transportName } from "./transport_net.js";
EOF
  else
    cat > "$TRANSPORT" <<'EOF'
/**
 * Transport selector.
 *
 * Re-exports the stub by default. `tools/build.sh --claude` rewrites this file
 * to point at ./transport_net.js. Keep the export surface identical in both.
 */
export { NET_AVAILABLE, postJson, transportName } from "./transport_none.js";
EOF
  fi

  STABLE="$stable" WITH_CLAUDE="$with_claude" \
  SERVER_VERSION="${SERVER_VERSION:-}" MIN_ENGINE="${MIN_ENGINE:-}" python3 - <<'EOF'
import json, os

stable = os.environ["STABLE"] == "1"
claude = os.environ["WITH_CLAUDE"] == "1"

# A manifest is parsed before anything else happens, so every value in it has to
# be something the player's version understands or the import is refused
# outright. Two rules follow:
#
#  - a dependency version must be a vector or a real SemVer string. "beta" is
#    neither; only 1.21.120+ special-cases it, and older games reject the whole
#    manifest.
#  - min_engine_version must not exceed the player's game, or the pack will not
#    import at all.
#
# Stable versions resolve forward like npm's "^" - a 2.0.0 dependency is
# satisfied by 2.7.0 - so one stable number covers every version from 1.21.80 to
# today. That is the default, and it is the only configuration that needs no
# knowledge of which release someone is on.
server_version = os.environ.get("SERVER_VERSION") or "2.0.0"
min_engine = [int(x) for x in (os.environ.get("MIN_ENGINE") or "1.21.80").split(".")]

bp = json.load(open("packs/AI_Citizens_BP/manifest.json"))
bp["header"]["min_engine_version"] = min_engine
deps = [d for d in bp.get("dependencies", []) if "module_name" not in d]
deps.append({"module_name": "@minecraft/server", "version": server_version})
deps.append({"module_name": "@minecraft/server-ui", "version": "2.0.0"})
if claude:
    # `optional` means a runtime without this module still loads the pack
    # instead of refusing it; the script already degrades to the local brain.
    deps.append({"module_name": "@minecraft/server-net",
                 "version": "1.0.0-beta", "optional": True})
bp["dependencies"] = deps
bp.get("metadata", {}).pop("generated_with", None)
json.dump(bp, open("packs/AI_Citizens_BP/manifest.json", "w"), indent=2)
open("packs/AI_Citizens_BP/manifest.json", "a").write("\n")

# The pack list shows this description, so the Beta APIs requirement is visible
# before anyone activates it rather than after it silently does nothing.
lang = ("pack.name=AI Citizens\n"
        "pack.description=%s\n"
        "entity.ai:citizen.name=Citizen\n"
        "item.spawn_egg.entity.ai:citizen.name=Spawn Citizen\n")
desc = ("Player-like AI settlers that mine, build, fight, talk and settle a town. "
        "Type /ai:spawn 4 to begin, then /ai:doctor if anything looks wrong.")
if not stable:
    desc = ("Player-like AI settlers that mine, build, fight, talk and settle a town. "
            "Needs the Beta APIs world toggle. Type /ai:spawn 4 to begin.")
open("packs/AI_Citizens_BP/texts/en_US.lang", "w").write(lang % desc)
EOF
}

package() {
  local suffix="$1"
  python3 - "$suffix" <<'EOF'
import os, sys, zipfile
suffix = sys.argv[1]

def add_tree(zf, src, prefix):
    for root, dirs, files in os.walk(src):
        dirs[:] = [d for d in dirs if d not in (".git", "__pycache__", "node_modules")]
        for name in files:
            if name.endswith((".pyc", ".DS_Store")):
                continue
            full = os.path.join(root, name)
            zf.write(full, os.path.join(prefix, os.path.relpath(full, src)))

def pack(out, entries):
    with zipfile.ZipFile(out, "w", zipfile.ZIP_DEFLATED) as zf:
        for src, prefix in entries:
            add_tree(zf, src, prefix)
    print("   %-38s %6.1f KB" % (out, os.path.getsize(out) / 1024))

os.makedirs("dist", exist_ok=True)
pack(f"dist/AI_Citizens{suffix}.mcaddon", [
    ("packs/AI_Citizens_BP", "AI_Citizens_BP"),
    ("packs/AI_Citizens_RP", "AI_Citizens_RP"),
])
EOF
}

rm -rf dist
mkdir -p dist

configure "$STABLE" "$WITH_CLAUDE"
echo "==> validating"
node tools/validate.mjs
echo "==> packaging"
package ""

echo "==> checking the package will import"
node tools/check-import.mjs dist/AI_Citizens.mcaddon

CHAT_ON=0
grep -q '"@minecraft/server",' /dev/null 2>&1 || true
if python3 -c "
import json,sys
m=json.load(open('packs/AI_Citizens_BP/manifest.json'))
d=[x for x in m['dependencies'] if x.get('module_name')=='@minecraft/server'][0]
sys.exit(0 if '-beta' in str(d['version']) or d['version']=='beta' else 1)"; then
  CHAT_ON=1
fi

echo
if [ "$CHAT_ON" -eq 1 ]; then
  echo "Built with chat listening (beta script API)."
  echo "  Turn on Beta APIs in the world, and make sure this build's pinned"
  echo "  version matches your Minecraft release, or it will not import."
  echo "  Then just talk to them:  @Ada go mine some iron"
else
  echo "Built for maximum compatibility: imports on any Minecraft 1.21.80+,"
  echo "no experiments needed, and it survives game updates."
  echo "  Spawn:  /ai:spawn 4"
  echo "  Talk:   /ai:tell @Ada go mine some iron"
  echo "  Check:  /ai:doctor"
fi
[ "$WITH_CLAUDE" -eq 1 ] && echo "Claude bridge enabled - see docs/CLAUDE_SETUP.md."
echo
echo "Install: open the .mcaddon, then activate both packs on your world."
