#!/usr/bin/env node
/*
 * Builds the standalone single-file app.
 *
 * Reads index.html, inlines the stylesheet and every module into it, and
 * writes sculpt.html — one file with no external references, which works
 * from a file:// URL with no server and no network.
 */
'use strict';

const fs = require('fs');
const path = require('path');

const here = __dirname;
const shell = fs.readFileSync(path.join(here, 'index.html'), 'utf8');

/* stylesheet */
const cssMatch = /<link rel="stylesheet" href="([^"]+)">/.exec(shell);
if (!cssMatch) throw new Error('No stylesheet link found in index.html');
const css = fs.readFileSync(path.join(here, cssMatch[1]), 'utf8');

/* modules, in the order the shell loads them */
const scriptRe = /<script src="([^"]+)"><\/script>\s*/g;
const sources = [];
let m;
while ((m = scriptRe.exec(shell))) sources.push(m[1]);
if (!sources.length) throw new Error('No module scripts found in index.html');

const code = sources.map((rel) => {
  const text = fs.readFileSync(path.join(here, rel), 'utf8');
  return `/* ===== ${rel} ===== */\n${text.trim()}\n`;
}).join('\n');

const version = (/S\.VERSION = '([^']+)'/.exec(
  fs.readFileSync(path.join(here, 'src/01-core.js'), 'utf8')) || [, '0'])[1];

const banner = `<!--
  SculptFree ${version} — standalone build
  Generated by build.js from index.html plus src/. Do not edit this file;
  edit the sources and run "node build.js" again.

  One file, no dependencies, no network: open it straight from disk.
-->`;

let out = shell
  .replace(/<link rel="stylesheet" href="[^"]+">/, () => `<style>\n${css.trim()}\n</style>`)
  .replace(scriptRe, '')
  .replace('</body>', `<script>\n${code}</script>\n</body>`)
  .replace('<!DOCTYPE html>', `<!DOCTYPE html>\n${banner}`);

/* the standalone build carries its own title marker so tests can tell them apart */
out = out.replace('<body>', '<body data-build="standalone">');

const target = path.join(here, 'sculpt.html');
fs.writeFileSync(target, out);

const bytes = Buffer.byteLength(out);
console.log(`sculpt.html written: ${(bytes / 1024).toFixed(0)} KB from ${sources.length} modules + ${(css.length / 1024).toFixed(0)} KB css`);

/* a quick sanity check: no leftover external references */
const external = out.match(/(?:src|href)="(?!data:|#)[^"]+"/g) || [];
if (external.length) {
  console.error('WARNING: external references remain:', external.join(', '));
  process.exitCode = 1;
}
